version: "3.8"

services:
  nuxt:
    container_name: frontend-proyecto
    image: node:18.20.2-alpine3.18
    user: 1000:1000
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0